name: Build LoopFollow on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          bundle exec pod install

      - name: Run Fastlane build
        env:
          TEAMID: ${{ secrets.DEVELOPER_APP_ID }}
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
        run: |
          bundle exec fastlane build_LoopFollow
